{% set version = "2.0.4" %}

package:
  name: pyhamcrest
  version: {{ version }}

source:
  fn: PyHamcrest-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/P/PyHamcrest/PyHamcrest-{{ version }}.tar.gz
  md5: d41d8cd98f00b204e9800998ecf8427e

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - six

test:
  imports:
    - hamcrest
    - hamcrest.core
    - hamcrest.core.core
    - hamcrest.core.helpers
    - hamcrest.library
    - hamcrest.library.collection
    - hamcrest.library.integration
    - hamcrest.library.number
    - hamcrest.library.object
    - hamcrest.library.text

about:
  home: https://github.com/hamcrest/PyHamcrest
  license: BSD 3-Clause
  summary: 'Hamcrest framework for matcher objects'

extra:
   recipe-maintainers:
      - duncanwp
      - stuertz
