{% set version = "1.10.1" %}

package:
  name: pyhamcrest
  version: {{ version }}

source:
  fn: PyHamcrest-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/P/PyHamcrest/PyHamcrest-{{ version }}.tar.gz
  md5: 6be265e4704aacd20cf8e4dd4eeb7dd3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - six

test:
  imports:
    - hamcrest
    - hamcrest.core
    - hamcrest.core.core
    - hamcrest.core.helpers
    - hamcrest.library
    - hamcrest.library.collection
    - hamcrest.library.integration
    - hamcrest.library.number
    - hamcrest.library.object
    - hamcrest.library.text

about:
  home: https://github.com/hamcrest/PyHamcrest
  license: BSD 3-Clause
  summary: 'Hamcrest framework for matcher objects'

extra:
   recipe-maintainers:
      - duncanwp
      - stuertz
