{% set version = "1.9.0" %}

package:
  name: pyhamcrest
  version: {{ version }}

source:
  fn: PyHamcrest-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/P/PyHamcrest/PyHamcrest-{{ version }}.tar.gz
  md5: 8b833a3fa30197455df79424f30c8c3f

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six

test:
  imports:
    - hamcrest
    - hamcrest.core
    - hamcrest.core.core
    - hamcrest.core.helpers
    - hamcrest.library
    - hamcrest.library.collection
    - hamcrest.library.integration
    - hamcrest.library.number
    - hamcrest.library.object
    - hamcrest.library.text

about:
  home: https://github.com/hamcrest/PyHamcrest
  license: BSD 3-Clause
  summary: 'Hamcrest framework for matcher objects'

extra:
   recipe-maintainers:
      - duncanwp
      - stuertz
