travis:
  secure:
    BINSTAR_TOKEN: jgUHQQaM3VDDvBeMWkBPIn5DZ8b4tr5HuVBDqks4dWtLRZSKmdOuUJHbgI2wP9mWegnQuxtdAZR2FWRsS/B3XJ0Khsi8/TnVS7sFADfCrbV8nOx5zhNfXHdLR5FdP9wKCdDkvm0Hffg0kuSKGPk1yuTjnw9mXsqsgyyGtOFR+LAoI2veMlwe3AVUIvrJEmShKLd4H6y5JmZYoDV8ysf23DPNN+WN67hs/I9hUa/UNRyuYh4gK/lQ6D9pb1ABnBcnWuS0uQ0jOtNHMi9lqX5sJJO5MKR1psApHf4v1V96TxgM9izmElA0B2tMivSv1itAeMCjUaBQCL+DvAKCcg7g5zbIAzN8CXGwLohaoDocqlsJU2EaGnioQh3WENDaReRzZcAhkmsKpYkDVcvzsTSoFvVXZN1EM4+/k/I9WWCmvpzj+kfe2fkuioe+dROY//5KGj+NWRc8evTyAvE4L63WRAb4gP4eZEMEnVY5XWBgCUA4FN5tmXV9THfocr0lO0WWDINmWv7Gx0QyijlUqSgs4zJFBJLfzi0YZg2zd2IrB5cDrYCrvwJho7/QuP6AwebUIvy9waddkPuVDsYLC2yL/MSZvg33oj3+OeW/2Cnwx2o7JrHO1hjsavBhz3zSKEeEL7jQ2ZzhAVDngokzqw78nS4OZRr+LRL+JOLvaA3MQFg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
