travis:
  secure:
    BINSTAR_TOKEN: QUN7I8ADP5RjO7wid6jsIXOMfQAkXPMNODUF+n552yTeQ6X3uvrxjk+M7o3VjZL2/2P3czDm2GUEHkxpMOf3VMLYpc5jeKrFN39oPYuF2qr0NoM+r5z86xR233tVDE+hFqTbmnTCfkje4ogEhfHOyesmvGUYF5+dBiX5mGCWqTc9SQX0s6mm7UA1YFUHm8nN89R/nofbU6iX0KiCGilwqwIdMg6LX+BzNhFFdUmVJoEtPxFGVfQTRmAzXhUI/5M9N+lwxAHTCxY4jlA/OMg5OqfvmtJGG101KvLVBBH+7GEbgzLf7tGiDM552HdjKSUX6YFtHgiQmLRoMw7w82F7sprwez8bNqNzSFi7oZJq85DugMOlLAnMJwJljg15MA5p8myBCKz1+mO+FuGIqMYhiF640g0GJU1Gn2WLYJy8PS3lYwF4S+506AC/dODBU7BSmioi201HVTE4M1qWL6fhwO+hyby2atgCJfBkRvyiZFGjMT2LfjzODbAmy8iejCSjH1do5mtw2PGrPrgNrbRNzcECa5HmwnglhTMekzE+luQL7d5XS2QEJ0txF3R5HtDIJ40crHJGr5ZF4W8Nw1GxeAyuFUdDD6GIDpS0mArW4OY+RDC+nWy9KfBMPyyMTnVIcve/CZeOrWSBEkgKCwgggRbbiiuxgnByCivZZ/ljZXM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
